// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/permission.proto

package permissionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ContextType   string                 `protobuf:"bytes,4,opt,name=context_type,json=contextType,proto3" json:"context_type,omitempty"`
	ContextId     string                 `protobuf:"bytes,5,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_proto_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CheckPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckPermissionRequest) GetContextType() string {
	if x != nil {
		return x.ContextType
	}
	return ""
}

func (x *CheckPermissionRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_proto_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPermissionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_permission_proto protoreflect.FileDescriptor

const file_proto_permission_proto_rawDesc = "" +
	"\n" +
	"\x16proto/permission.proto\x12\n" +
	"permission\"\x9f\x01\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12!\n" +
	"\fcontext_type\x18\x04 \x01(\tR\vcontextType\x12\x1d\n" +
	"\n" +
	"context_id\x18\x05 \x01(\tR\tcontextId\"K\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2o\n" +
	"\x11PermissionService\x12Z\n" +
	"\x0fCheckPermission\x12\".permission.CheckPermissionRequest\x1a#.permission.CheckPermissionResponseBMZKgithub.com/kirulegion/Dissty/services/permission-service/proto/permissionpbb\x06proto3"

var (
	file_proto_permission_proto_rawDescOnce sync.Once
	file_proto_permission_proto_rawDescData []byte
)

func file_proto_permission_proto_rawDescGZIP() []byte {
	file_proto_permission_proto_rawDescOnce.Do(func() {
		file_proto_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_permission_proto_rawDesc), len(file_proto_permission_proto_rawDesc)))
	})
	return file_proto_permission_proto_rawDescData
}

var file_proto_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_permission_proto_goTypes = []any{
	(*CheckPermissionRequest)(nil),  // 0: permission.CheckPermissionRequest
	(*CheckPermissionResponse)(nil), // 1: permission.CheckPermissionResponse
}
var file_proto_permission_proto_depIdxs = []int32{
	0, // 0: permission.PermissionService.CheckPermission:input_type -> permission.CheckPermissionRequest
	1, // 1: permission.PermissionService.CheckPermission:output_type -> permission.CheckPermissionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_permission_proto_init() }
func file_proto_permission_proto_init() {
	if File_proto_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_permission_proto_rawDesc), len(file_proto_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_permission_proto_goTypes,
		DependencyIndexes: file_proto_permission_proto_depIdxs,
		MessageInfos:      file_proto_permission_proto_msgTypes,
	}.Build()
	File_proto_permission_proto = out.File
	file_proto_permission_proto_goTypes = nil
	file_proto_permission_proto_depIdxs = nil
}
